apiVersion: v1
kind: ConfigMap
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
data:
  welcome.message: "Yay !! hello from kubernetes"
  mgmt.endpts.webexp.include: info,health,palTrackerFailure
